name: CD

on:
  push:
    tags:
      - 'v*'

jobs:
  push-packages:
    name: Pack & Push
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .Net SDK 6.0.x
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: .Net Restore
        run: dotnet restore
      - name: .Net Build
        run: dotnet build --no-restore --configuration Release
      - name: .Net Test
        run: dotnet test --no-build --no-restore --configuration Release
      - name: .Net Pack
        run: dotnet pack src/Rezaee.Data.Iranseda --no-build --no-restore --configuration Release
      - name: Push to NuGet
        run: |
          dotnet nuget push src/Rezaee.Data.Iranseda/**/*.nupkg \
          --api-key ${{ secrets.NUGET_API_KEY }} \
          --source https://api.nuget.org/v3/index.json \
          --skip-duplicate
      - name: Push to GitHub
        run: |
          dotnet nuget push src/Rezaee.Data.Iranseda/**/*.nupkg \
          --api-key ${{ secrets.USER_PAT }} \
          --source https://nuget.pkg.github.com/alireza-rezaee/index.json \
          --skip-duplicate
